# What is pytorch?

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 4.6566e-10, 0.0000e+00],
        [4.6566e-10, 1.4569e-19, 2.7517e+12],
        [7.5338e+28, 3.0313e+32, 6.3828e+28],
        [1.4603e-19, 1.0899e+27, 6.8943e+34],
        [1.1835e+22, 7.0976e+22, 1.8515e+28]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.8694, 0.6412, 0.2065],
        [0.4348, 0.7436, 0.8368],
        [0.7674, 0.7899, 0.7544],
        [0.2222, 0.8647, 0.8122],
        [0.3131, 0.2145, 0.8250]])


In [4]:
x = torch.ones(5,4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
x = torch.ones(5,6, dtype=torch.float)

In [6]:
print(x)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [7]:
x = torch.tensor([5.5,4])
print(x)

tensor([5.5000, 4.0000])


In [12]:
x = torch.tensor([4,4])
print(x)

tensor([4, 4])


In [10]:
xx = torch.randn_like(x, dtype=torch.float)

In [11]:
print(xx)

tensor([0.6081, 0.3947])


## Operations

In [15]:
y = torch.rand(2,1)
print(xx+y)

tensor([[1.1908, 0.9775],
        [1.2762, 1.0629]])
